# Generated by Django 2.2.15 on 2020-08-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='painters')),
            ],
        ),
    ]
