# Generated by Django 2.2.15 on 2020-08-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painter',
            old_name='photo',
            new_name='picture',
        ),
    ]
