# Generated by Django 2.2.15 on 2020-08-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painter', '0002_auto_20200825_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painter',
            name='country',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='painter',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='painter',
            name='surname',
            field=models.TextField(max_length=200),
        ),
    ]
