# Generated by Django 2.2.15 on 2020-08-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painter', '0005_auto_20200825_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='painter',
            old_name='name',
            new_name='firstname',
        ),
    ]
